# Generated by Django 3.2.9 on 2021-11-11 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211108_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 13, 48, 59, 181377)),
        ),
    ]
